// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAXXO8FJlnkjoGmAcM0CiQnrsWhNgclnM',
    appId: '1:322768787009:web:b89bf3c79a01fc944658c0',
    messagingSenderId: '322768787009',
    projectId: 'note-now-ab98b',
    authDomain: 'note-now-ab98b.firebaseapp.com',
    storageBucket: 'note-now-ab98b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBTdwdXEK6dgL7YJLzXLZ2Y2DOBk9i0zk',
    appId: '1:322768787009:android:231858fc488763784658c0',
    messagingSenderId: '322768787009',
    projectId: 'note-now-ab98b',
    storageBucket: 'note-now-ab98b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKbQYxmhzi7-sF9wycob0oXQN0FoUFzRk',
    appId: '1:322768787009:ios:edfb816660cb61014658c0',
    messagingSenderId: '322768787009',
    projectId: 'note-now-ab98b',
    storageBucket: 'note-now-ab98b.firebasestorage.app',
    iosBundleId: 'com.example.noteNow',
  );
}
